<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DC4-QVM-TMQA-08" name="ExtentWithParallelClasses1(failed)" tests="1" failures="1" timestamp="7 Feb 2019 10:59:26 GMT" time="27.218" errors="0">
  <testcase name="TC4" time="19.764" classname="com.pulse.Test.ValidLogin2">
    <failure type="java.lang.AssertionError" message="expected [Yahoo1] but found [Yahoo]">
      <![CDATA[java.lang.AssertionError: expected [Yahoo1] but found [Yahoo]
	at com.pulse.Test.ValidLogin2.TC4(ValidLogin2.java:115)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- TC4 -->
</testsuite> <!-- ExtentWithParallelClasses1(failed) -->
